import { getRecommendations } from '../lib/careerEngine'

export default function Explainability({ profile }) {
  const { top } = getRecommendations(profile)

  // Find dominant traits
  const sortedTraits = Object.entries(profile.traits).sort(([, a], [, b]) => b - a)
  const topTraits = sortedTraits.slice(0, 3)

  const traitLabels = {
    Linguistic: 'linguistic ability',
    Logical_Mathematical: 'analytical & logical reasoning',
    Spatial_Visualization: 'spatial visualization',
    Interpersonal: 'interpersonal skills',
    Intrapersonal: 'self-awareness',
    Musical: 'musical intelligence',
    Bodily: 'bodily-kinesthetic skills',
    Naturalist: 'nature affinity',
  }

  const whySuited = `Your profile shows strong ${topTraits.map(([t]) => traitLabels[t]).join(', ')}. 
    The ${top.title} career path heavily rewards these traits, making it an excellent match for your cognitive style and strengths. 
    The career aligns particularly well with your ${traitLabels[topTraits[0][0]]} (score: ${topTraits[0][1]}/10).`

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="w-1 h-8 bg-indigo-500 rounded-full"></div>
        <div>
          <h2 className="text-2xl font-bold text-white">Why This Career?</h2>
          <p className="text-slate-400 text-sm mt-0.5">AI-generated explanation for your top match</p>
        </div>
      </div>

      {/* Career title */}
      <div className="bg-slate-900 border border-slate-700 rounded-xl p-5">
        <p className="text-sm text-slate-400 mb-1">Explaining recommendation for</p>
        <h3 className="text-2xl font-bold text-white">{top.title}</h3>
        <p className="text-indigo-400 text-sm mt-1">{top.domain}</p>
      </div>

      {/* Key Strengths */}
      <div className="bg-slate-900 border border-slate-700 rounded-xl p-6">
        <div className="flex items-center gap-2 mb-4">
          <span className="text-amber-400 text-lg">💡</span>
          <h3 className="text-base font-semibold text-white">Key Strengths Identified</h3>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          {top.strengths.map((s, i) => (
            <div key={i} className="flex items-start gap-3 bg-amber-950/20 border border-amber-900/40 rounded-lg p-4">
              <span className="text-amber-400 font-bold text-lg mt-0.5">✦</span>
              <span className="text-sm text-amber-200">{s}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Dominant Traits */}
      <div className="bg-slate-900 border border-slate-700 rounded-xl p-6">
        <div className="flex items-center gap-2 mb-4">
          <span className="text-indigo-400 text-lg">📊</span>
          <h3 className="text-base font-semibold text-white">Your Dominant Traits</h3>
        </div>
        <div className="space-y-3">
          {topTraits.map(([trait, score]) => (
            <div key={trait}>
              <div className="flex justify-between text-sm mb-1">
                <span className="text-slate-300">{traitLabels[trait]}</span>
                <span className="text-indigo-400 font-semibold">{score}/10</span>
              </div>
              <div className="w-full bg-slate-800 rounded-full h-2">
                <div
                  className="bg-indigo-500 h-2 rounded-full"
                  style={{ width: `${score * 10}%` }}
                ></div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Summary */}
      <div className="bg-gradient-to-br from-indigo-950/60 to-slate-900 border border-indigo-800/50 rounded-xl p-6">
        <div className="flex items-center gap-2 mb-3">
          <span className="text-indigo-400 text-lg">🤖</span>
          <h3 className="text-base font-semibold text-white">AI Explanation Summary</h3>
        </div>
        <blockquote className="text-slate-300 text-sm leading-relaxed border-l-2 border-indigo-500 pl-4 italic">
          "{whySuited}"
        </blockquote>
        <p className="text-xs text-slate-600 mt-3">Generated by the Agentic Career Reasoning Engine · Based on Gardner's Multiple Intelligence Framework</p>
      </div>
    </div>
  )
}
